### ISSUE TITLE
在？修个bug？

### ISSUE THREAD

**Issue by Summersummer3** [leeif/mercury#7]
go sdk: 1.18.1

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13bd21e]

goroutine 1 [running]:
github.com/go-kit/log/level.NewFilter(...)
        /Users/summer/go/pkg/mod/github.com/go-kit/log@v0.2.0/level/level.go:35
github.com/go-kit/kit/log/level.NewFilter({0x17e4960?, 0xc000205180}, {0xc0002a1000, 0x1, 0xc00020e228?})
        /Users/summer/go/pkg/mod/github.com/go-kit/kit@v0.12.0/log/level/level.go:34 +0x7e
github.com/leeif/mercury/log.NewLogger(0x1?)
        /Users/summer/workspace/mercucy/mercury/log/log.go:20 +0x286
reflect.Value.call({0x160bcc0?, 0x173b458?, 0x100e865?}, {0x16f2620, 0x4}, {0xc00020e258, 0x1, 0x30?})
        /Users/summer/sdk/go1.18.1/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x160bcc0?, 0x173b458?, 0x100ebc7?}, {0xc00020e258, 0x1, 0x1})
        /Users/summer/sdk/go1.18.1/src/reflect/value.go:339 +0xbf
go.uber.org/dig.defaultInvoker({0x160bcc0?, 0x173b458?, 0xc0002045f0?}, {0xc00020e258?, 0x1?, 0x17ee2a0?})
        /Users/summer/go/pkg/mod/go.uber.org/dig@v1.14.1/container.go:220 +0x28
go.uber.org/dig.(*constructorNode).Call(0xc000240180, {0x17ee2a0, 0xc00021e140})
        /Users/summer/go/pkg/mod/go.uber.org/dig@v1.14.1/constructor.go:154 +0x297
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x17ef400, 0x1641bc0}}, {0x17ee2a0, 0xc00021e140})
        /Users/summer/go/pkg/mod/go.uber.org/dig@v1.14.1/param.go:296 +0x2f9
go.uber.org/dig.paramList.BuildList({{0x17ef400, 0x162c820}, {0xc00020c940, 0x4, 0x4}}, {0x17ee2a0, 0xc00021e140})
        /Users/summer/go/pkg/mod/go.uber.org/dig@v1.14.1/param.go:151 +0xb9
go.uber.org/dig.(*Scope).Invoke(0xc00021e140, {0x162c820?, 0x173b460}, {0xc000204a30?, 0x1?, 0x1?})
        /Users/summer/go/pkg/mod/go.uber.org/dig@v1.14.1/invoke.go:85 +0x288
go.uber.org/dig.(*Container).Invoke(...)
        /Users/summer/go/pkg/mod/go.uber.org/dig@v1.14.1/invoke.go:46
go.uber.org/fx.(*App).executeInvokes(0xc000232000)
        /Users/summer/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:547 +0x198
go.uber.org/fx.New({0xc0002a1f30, 0x3, 0x1?})
        /Users/summer/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:345 +0x445
main.main()
        /Users/summer/workspace/mercucy/mercury/main.go:24 +0x185
exit status 2

看起来是缺了基础配置文件？./mc.cnf.toml

**Comment by Summersummer3** [comment]
go get pluto version 错误, 暂时没用可以删掉

**Comment by jimga150** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
GarrickLin, @ahua772, @joem99, @tavernier, @wlevel, @duwanqiebi, @nirocfz, @bingelaoda, @YugenFring, @nethong, @Derrick-Wang, @lixuan11, @Junsy66, @chenshiwei-io, @javabean7, @MerryYou, @zouyuefen, @lichuang, @Martinho0330, @lijialiang
